trigger:
  branches:
    include:
    - main
  paths:
    include: 
    - src/redis/.azure-pipelines/cicd.yml

pool: Linux

stages:
- template: ../../.azure-pipelines/templates/cd.tpl.yml
  parameters:
    appName: redis
    env: dev