parameters:
  - name: appName
    type: string

stages:
- stage: Publish
  displayName: "Publish"
  jobs:
  - job:
    variables:
      containerRegistry: AzureCR
    steps:
    - checkout: self
      clean: true
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: ${{ variables.containerRegistry }}
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: ${{ parameters.appName }}
        Dockerfile: "src/${{ parameters.appName }}/Dockerfile"
        tags: latest
- template: cd.tpl.yml
  parameters:
    appName: ${{ parameters.appName }}
    env: dev